### PR TITLE
Priority Support banner

### PR DESCRIPTION
**Pull request by ezequielc**
Stage link: https://apps-stage-1.risevision.com/
@alex-deaconu Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . 

One thing I'd like to bring up. When checking the Priority Support subscription status, we use the Selected Company Id. Wondering if we should check instead if the User's Company is subscribed? Thoughts?

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Good question. I think it is OK to use Selected Company Id as the subscription is Company related. I guess we will cover some use cases and miss others.
I checked Priority Support modal and it uses Selected Company as well: https://github.com/Rise-Vision/common-header/blob/master/src/js/svc-support-factory.js#L71 So at least we are consistent.
Thoughts? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc agreed re: consistency with the modal. 

However, as a user who has purchased support for their company, I should be able to access priority support in my sub-companies as well. Currently, I'd have to switch back to my original company to open the support modal. It would be an inconvenience, and I'm wondering if it could lead to someone buying it twice by mistake.

Either way, this is just something to keep in mind for the future. I don't think it affects this PR. 

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Makes sense. Thanks!

**Pull request merged**
