### PR TITLE
Updating common header version

### PR DESCRIPTION
**Pull request by jasoncaldwell**

### CODE REVIEW

**Comment by jasoncaldwell** [comment]
@alex-deaconu Copy that, thanks! So ... I should review this on Stage 1 before we merge into Production?

**Comment by alex-deaconu** [comment]
@jasoncaldwell no, I've reviewed locally and everything is ok. It's already merged. 

Here's an example from my PR:
Screen Shot 2019-06-05 at 11 23 08 AM

https://github.com/Rise-Vision/rise-vision-apps/pull/1014.

It's is staged on stage-2.

Thanks.

**Comment by jasoncaldwell** [comment]
@alex-deaconu Great! Stage 2 looks good to me, too. And then, what's the process for getting staging into production?

**Comment by alex-deaconu** [comment]
@jasoncaldwell merging to master automatically deploys the changes to production.

**Comment by jasoncaldwell** [comment]
@alex-deaconu Perfect, thanks!

**Pull request merged**
