### PR TITLE
New layout for Store Products Modal

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc I know this is not a coding issue, but looking at the `Add Widget by URL` button it seems like it's floating over the list: http://screencast.com/t/H4tWVI86. Maybe some padding at the top or a border, or both would help? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I agree, I will try to add. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc another styling question. I'm wondering if it would look better if the items on the last row were left aligned: http://screencast.com/t/DAYkEeZ73? Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc code looks good :+1: . Just 2 styling questions above. Thanks.

**Comment by ezequielc** [comment]
Thanks @alex-deaconu ! I will defer to @RV-Adrian and @ghislaineguerin on that. Cheers!

**Comment by ezequielc** [comment]
@alex-deaconu I am getting a scroll bar whenever I add top margin. @RV-Adrian or @ghislaineguerin  Could you take a look at this? Thanks!

**Comment by ezequielc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Gg3tbKoh&#x2F;1008-new-app-launcher-page-store-modal-2"> New App Launcher page - Store Modal [2]</a>

**Comment by ghislaineguerin** [comment]
@alex-deaconu I have implemented both style changes that you suggested.

**Comment by alex-deaconu** [comment]
@ghislaineguerin I don't think this staged correctly due to a CCI error. There is a conflict with the bower branch names. Thanks.

**Pull request merged**
