### PR TITLE
Fix/text tables

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
Please validate fix for Issue https://github.com/Rise-Vision/rise-vision-apps/issues/323 
on https://apps-stage-3.risevision.com/displays/details/VH3CKAHZQ5P7

The Display ID cell should show a Text cursor on hover, and be selectable with a double-click.

**Comment by ezequielc** [comment]
@RV-Adrian I am wondering if we should have the same behaviour for the whole row as we might need to select other cells there too. Thoughts?

**Comment by RV-Adrian** [comment]
@ezequielc I was planning to change the behaviour of the Pointer cursor on the other table columns (not a bug necessarily, but seems odd). Can we tackle Table text selection outside of this Issue? (since it did focus on Display ID) Thx

**Comment by ezequielc** [comment]
@RV-Adrian Sounds good, we can release it as it will fix the issue, but we should add a card to our tech debt. Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian 👍

**Comment by RV-Adrian** [comment]
@ezequielc Makes sense! Thanks

**Comment by alex-deaconu** [comment]
@RV-Adrian my question is why those table rows are non-selectable in general? I think you should address that as well as the cursor in the future work. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Sorry, yes that's what I meant -- why they're indicating a 'click' function and not typical HTML text 👍

**Pull request merged**
