### PR TITLE
Fix auth pages styling

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Fix auth pages styling

Partial implementation for sign up sidebar
Commented out until finalized

[stage-19]

## Motivation and Context
Styling fixes for the main PR.

## How Has This Been Tested?
Tested changes locally.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Styling fixes only. Will fix e2e tests in a separate PR.

@ezequielc please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc last commit fixes the mobile width. Thanks!

**Review by ezequielc — APPROVED** [review]

**Comment by alex-deaconu** [comment]
@ezequielc also fixed editor background color in the latest commit. Thanks!

**Comment by ezequielc** [comment]
Thanks @alex-deaconu , looks good 👍

**Pull request merged**
