### PR TITLE
Add help button in header for logged in users

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps please review

### CODE REVIEW

**Comment by ezequielc** [comment]
@fjvallarino Is this on stage-4? I am testing it and it is not working very well on the sign in page.
It works fine when I load the page for the first time, but if I reload it, the Help button in the corner doesn't show. Could you try? Thanks

**Comment by fjvallarino** [comment]
@ezequielc it's fixed now

**Comment by fjvallarino** [comment]
@ezequielc @alex-deaconu before merging to master, a new release of Common Header is required: https://github.com/Rise-Vision/common-header/pull/816

**Comment by ezequielc** [comment]
@fjvallarino Thanks!

**Pull request merged**
