### PR TITLE
remove param value showui=false from scheduleFactory.getPreviewUrl()

### PR DESCRIPTION
**Pull request by settinghead**

### CODE REVIEW

**Comment by ezequielc** [comment]
@settinghead I believe your tests are failing for the same reason as @fjvallarino found out yesterday. Angular was updated to 1.6 and it removed $http.success(). A quick workaround is to force angular version to 1.5. Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc do you think we should consider fixing instead? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think we should add a separate card for the fix. It might require updating other repos and I am not sure if @settinghead has the availability to do that right now. Thoughts?

**Comment by alex-deaconu** [comment]
@ezequielc okay.

**Comment by settinghead** [comment]
@alex-deaconu @ezequielc @fjvallarino I'll do an update shortly, because I will need this update to get the PR merged. Thanks.

**Comment by settinghead** [comment]
@Rise-Vision/apps the build is now fixed. @fjvallarino Thanks for the tip.

**Comment by alex-deaconu** [comment]
@settinghead 👍

**Pull request merged**
