### PR TITLE
Send information email to user on Display creation

### PR DESCRIPTION
**Pull request by alex-deaconu**
[stage-2]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Works perfectly! Code looks good :+1: Thanks

**Comment by alex-deaconu** [comment]
@ezequielc curious, you think I should merge this as is or wait for the Display modal changes where we inform the User that an email has been sent? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think you should merge, the email is very helpful. I don't see a problem if we don't inform the user before sending it. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc sounds good. Merging. Thanks!

**Pull request merged**
