### PR TITLE
Show Storage spinner when loading list

### PR DESCRIPTION
**Pull request by alex-deaconu**
Reworked show/hide logic
Moved empty state partial to list

Misc fixes:
Spinner fix from common-style

Removed un-used variable
Fixed filter initialization

Only show select files/folders CTA for specific selector type

Fix Displays list empty state

JSHint fixes

[stage-4]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fixes the following issues:

- Spinner does not show when loading storage modal
- Storage empty state does not show in full screen storage
- Incorrect empty state CTA for Single File selector
- Once Image/Video Selector is opened, going to Storage full persists filter

- All spinners are full screen instead of part of the table
- Displays list empty state does not show

@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Nice work. 👍  Thanks for fixing!
Don't forget to update common-style branch. Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc updated, thanks for the reminder 🎉

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Pull request merged**
