### PR TITLE
Fix issue #69 - Hide modals on state change

### PR DESCRIPTION
**Pull request by ezequielc**
[stage-2]

@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc interesting solution! I didn't know that was possible - @olegrise FYI, you may want to take a look as well.

However, I've had issues where I was pressing the Delete key, thinking I was deleting from a textbox and I back navigated instead (losing my form data). Should we maybe disable Delete key navigation completely?

Also, do you think we should move this code to common-header so its common to all our projects? 

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Thanks! 
As we have a card for notifying unsaved changes, I think it is redundant to disable Delete key. Thoughts? 
Regarding moving the code to CH, I think it is a good suggestion. I will do that. 
Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc sounds good on both points. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu @ezequielc interesting solution. I didn't know about that. 
It might be useful in some situations, but not everywhere. For example we had few situations when a user would open a Payment Form in the Store, start filling it in, then at some point click on the Country dropdown, select a country and then push Delete key. Not sure what they expected the Delete key to do, but definitely not to close the modal and loose all the data they just entered. Cheers.

**Comment by alex-deaconu** [comment]
@olegrise interesting point. @ezequielc FYI.

I dug up the Store PR which fixes the similar issue: https://github.com/Rise-Vision/store/pull/1098/files.

Personally, I'm not a fan of adding the specific code to every modal. However, I think with this handler (in the CH) we would deal with all situations, and the Store modal specific handler 'should' override this one, right?

Also, one thing I noticed, Store doesn't un-register its handlers on controller unload... may be an issue for backspace navigation elsewhere in the Store after one of those modals is opened.

Thanks.

**Comment by olegrise** [comment]
@alex-deaconu what do you mean "_Store doesn't un-register its handlers on controller unload_"? 

@alex-deaconu @ezequielc I thought about this a little more. When I put myself into user shoes, I don't know if I would hit the Delete key in order to close the module. You see what I mean? They probably expect something else to happen. Closing the module or showing  a message "Do you want to save your changes" would be completely unexpected. Maybe I don't understand your use case.

**Comment by alex-deaconu** [comment]
@olegrise http://stackoverflow.com/questions/26983696/angularjs-does-destroy-remove-event-listeners. Disregard that statement, according to the article I believe we're ok. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu LOL. I was just looking at the same article.

**Comment by alex-deaconu** [comment]
@olegrise @ezequielc wondering if my original suggestion of disabling Delete Key navigation specifically  would work for us. Sounds like quite a hack, however (http://stackoverflow.com/questions/1495219/how-can-i-prevent-the-backspace-key-from-navigating-back). 

Thanks!

**Comment by olegrise** [comment]
@ezequielc @alex-deaconu curious, have you guys discussed the UX for this use case with @RV-Adrian and @ghislaineguerin ?

**Comment by ezequielc** [comment]
@olegrise @alex-deaconu I think we have two different scenarios here.

Scenario 1: When starting a new presentation, Presentation Properties modal opens. If I go back in history (either Delete key or browser back button), I will go back to Presentations List but the modal will still appear. This is the issue I fixed.

Scenario 2: When filling a form in a modal, I accidentally pressed Delete and I was sent back in navigation history. For this case, I agree that we should disable Delete key.

Thoughts? Thanks

**Comment by olegrise** [comment]
In my opinion disabling Delete key will work well for both scenarios @alex-deaconu @ezequielc

**Comment by RV-Adrian** [comment]
@olegrise @ezequielc @alex-deaconu 
Apologies if this is obvious --
if the user is filling in a form, and 'Delete' is disabled... how do I delete text?
I'm thinking that if text input fields enable 'Delete' while they have focus, we should be good?

**Comment by ezequielc** [comment]
@RV-Adrian Yes, we need to handle that case and enable Delete for input fields.

@alex-deaconu @olegrise @RV-Adrian
To summarize, I will move this code to CH and add a code to disable Delete key. Do you guys agree?

Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc works for me. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc Great 👍

**Comment by olegrise** [comment]
@ezequielc works for me. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu @RV-Adrian I just had a conversation with @olegrise and we defined that:

1)  we will disable Delete key from CH code
2)  we will dismiss modal when navigating back in history from Apps code, as it is a specific need and it could potentially affect current behavior elsewhere.

Do you guys agree? Thanks!

**Comment by olegrise** [comment]
@ezequielc agreed. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc works for me, thanks!

**Comment by RV-Adrian** [comment]
@ezequielc awesome, thanks

**Comment by ezequielc** [comment]
@alex-deaconu Please review. Staged at https://apps-stage-2.risevision.com. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc code looks good 👍 . Just waiting for the CH updates that @olegrise suggested. Thanks!

**Pull request merged**
