### PR TITLE
Fix/accordion ui

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @fjvallarino 
Please review:
I tried to change the e2e tests to get it to work with the new '.progress-panel' class, but no luck.
Thx!

**Comment by alex-deaconu** [comment]
@RV-Adrian I'll take a look at e2e tests and try to fix. Thanks.

**Comment by alex-deaconu** [comment]
@RV-Adrian looks good. I tested Display page Reboot command, Uploading, Downloading, Deleting, Restoring, etc. All works and looks as expected 👍 . Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Thanks! Okay if I merge this before Zoom-Fit?

**Comment by alex-deaconu** [comment]
@RV-Adrian yup, go ahead. I'll rebase that and merge. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu 
Just a headsup I am having some build errors that seems related to sign in. Will keep at it
https://4341-38897323-gh.circle-artifacts.com/1/tmp/circle-junit.LrYxquC/screenshots/storage_selector_given_a_user_who_wants_to_set_a_background_image__before_all__hook.png

**Comment by RV-Adrian** [comment]
@alex-deaconu Scratch the above 👍

**Pull request merged**
