### PR TITLE
Display added page

### PR DESCRIPTION
**Pull request by alex-deaconu**
Disable displays e2e tests

[stage-1]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Implements 2 screens for the Add Display flow.

@Rise-Vision/apps please review. Thanks!

**Comment by alex-deaconu** [comment]
Just FYI I will merge to the main branch despite the constantly failing template editor tests. I think Content is working on fixing those. Thanks.

**Comment by olegrise** [comment]
@alex-deaconu makes sense

**Comment by alex-deaconu** [comment]
@olegrise as I mentioned, I've updated the HTML a little bit for the page, to use existing/new utilities rather than custom classes. Thanks.

**Pull request merged**
