### PR TITLE
display status UI via messaging service

### PR DESCRIPTION
**Pull request by settinghead**

### CODE REVIEW

**Comment by settinghead** [comment]
@ezequielc @alex-deaconu please review. thanks.

**Comment by settinghead** [comment]
@ezequielc @alex-deaconu BTW, not sure if you are aware: you may append `?w=0` at the end of the file changes URL for a PR to filter out all changes related to space: 

https://github.com/Rise-Vision/rise-vision-apps/pull/270/files?w=0

**Comment by ezequielc** [comment]
@settinghead I am getting a warning:
"WebSocket connection to 'wss://display-messaging.risevision.com:3000/primus?_primuscb=LVOLB4Q' failed: WebSocket is closed before the connection is established." 
Is this expected? Thanks

**Comment by settinghead** [comment]
@ezequielc yeah I see it too. I don't know the exact cause of this particular case, but I've seen this particular warning in quite a few other websocket-enabled projects with different libraries, but in all those cases the warning does not affect functionality. What the websocket library end up doing is simply re-open a new connection and resume communication. That said, I think the warning is likely benign.

**Comment by tejohnso** [comment]
@ezequielc @settinghead Where is that connection attempt coming from?  The connection shouldn't be to /primus

**Comment by settinghead** [comment]
@tejohnso @ezequielc the connection is spawned by Primus client, which I believe was initiated via connection to `https://display-messaging.risevision.com:3000`. In the code there is no mention of connecting to `/primus`, so I think that part is auto-generated and negotiated by the server.

**Comment by settinghead** [comment]
@tejohnso @ezequielc here is a screenshot on the websocket frames:

image

It looks correct, because in the websocket frames the client managed to send a `present-request` and the server managed to respond accordingly.

**Comment by ezequielc** [comment]
@settinghead While the request to Messaging Service is not completed, I believe you are showing in the UI the original status from Core. 
In the mockups, we had a small spinner being showed while the status was not ready. Would you mind adding that? 
My suggestion is to add `statusLoading` flag to the display service and use it in the partial to show/hide the spinner. Thanks!

**Comment by settinghead** [comment]
@ezequielc sure will do.

**Comment by ezequielc** [comment]
@settinghead I reviewed the spinner code and it looks good. I think you missed updating the details page. Cheers!

**Comment by settinghead** [comment]
@ezequielc added the missing display details case. Please review. Thanks!

**Comment by settinghead** [comment]
@ezequielc updated with animated spinner. Thanks.

**Comment by settinghead** [comment]
apps_common_storage_selector_given_a_user_that_just_signed_up_for_rise_vision__before_all__hook
@ezequielc I may have found some clue on why the E2E tests are failing (see screenshot above).

It seems that the page in the above Selenium screenshot is shown for every single E2E tests, completely disrupting the test flow.

Any idea why this is happening? A recent change in the Google accounts?

@alex-deaconu @tejohnso @fjvallarino FYI

**Comment by ezequielc** [comment]
@settinghead Yes, this page is shown when the user signs in for the first. It seems that our test company was deleted. We might need to recreate it. Cheers

**Comment by settinghead** [comment]
@ezequielc All set, should be ready to merge.
(BTW I messed up the rebase a little, but the end result is I re-pointed the base for this PR, so merging this PR will merge the implementation directly into `master`.

**Comment by ezequielc** [comment]
@settinghead Code looks good 👍 Thanks!

**Pull request merged**
