### PR TITLE
CH v1.13.22 - change URL for Ask Sales button

### PR DESCRIPTION
**Pull request by olegrise**
@alex-deaconu the build keeps failing for this PR. I'm not sure if it's something that I broke or it's a common situation. Please advise.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise unfortunately that's how it is. Apps e2e tests are very unreliable. Will keep trying for you until it passes. Thanks.

**Comment by olegrise** [comment]
Thanks @alex-deaconu

**Comment by olegrise** [comment]
@alex-deaconu please review :)

**Comment by alex-deaconu** [comment]
@olegrise looks good 👍

**Pull request merged**
