### PR TITLE
Fix/install anim

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ezequielc @alex-deaconu @settinghead 
PR for issue at https://github.com/Rise-Vision/rise-vision-apps/issues/249

Last comment contains staged link and validation info.

Dependant Common-Style PR at https://github.com/Rise-Vision/common-style/pull/272

### CODE REVIEW

**Comment by ezequielc** [comment]
@RV-Adrian For the PRs, we need to have e2e enabled. It sometimes fails 2 or 3 times before it passes. If it does not, let me know and I will try to fix it. It is a known issue and we have a solution to auto-retry as a future improvement. Sorry about that. Thanks!

**Comment by settinghead** [comment]
@RV-Adrian second what @ezequielc said (there was one case where I tried 5 times on the same commit before it managed to pass the E2E test).

**Comment by RV-Adrian** [comment]
@ezequielc @settinghead Gotcha! Wasn't sure if there was some workaround yet. Added e2e back to both PRs, and both are now staged successfully. Thanks!

**Comment by settinghead** [comment]
@RV-Adrian LGTM

**Comment by ezequielc** [comment]
@RV-Adrian 👍 Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian 👍 . Please squash before merging. Thanks!

**Pull request merged**
