### PR TITLE
Navigation update 

### PR DESCRIPTION
**Pull request by ezequielc**
Staged at https://apps-stage-4.risevision.com/

@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc should we be updating the `Editor` name in the CH app launcher dropdown as well? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Yes, makes sense to me. @RV-Adrian what about you? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc actually, just noticed @ghislaineguerin already created a branch for that: https://github.com/Rise-Vision/common-header/compare/feature/update-navigation?expand=1. Can just re-use. Thanks.

**Comment by ezequielc** [comment]
Sorry @alex-deaconu, I missed it. I will update. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu Sounds good. I noticed a gap here http://goo.gl/wENZmE
If it's still there after update let me know, thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Please review. Thanks!

**Comment by alex-deaconu** [comment]
:+1:

**Pull request merged**
