### PR TITLE
Empty state issue fix [stage-1]

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @fjvallarino 
Please see apps-stage-1.risevision.com/
for issue fix: https://trello.com/c/63dd8Gl0/2086-issue-350-app-empty-states-are-misaligned-not-functional-1

You'll have to use an account with no assets to see empty states for Presentations/Schedules/Displays

I've also included a PR for common-i18n to use sentence case as per branding guide:
https://github.com/Rise-Vision/common-i18n/pull/209

**Comment by alex-deaconu** [comment]
@RV-Adrian looks good 👍 . Just a quick note in the common-i18n PR. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Got it, bumped the version. Thanks for quick response!

**Comment by alex-deaconu** [comment]
@RV-Adrian you forgot to remove the branch name from `bower.json` prior to merging. Wondering if you can just do a second, quick PR to fix that? In the meantime I have restored the branch in common-i18n so the build will pass. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Thanks for catching that! Removing the reference now.

**Pull request merged**
