### PR TITLE
List view for component storage selector

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
List view for component storage selector

Allow user to choose list/grid view
List view is default
Allow sort by both columns
Checkboxes for selection & select all functionality

[stage-2]

## Motivation and Context
Allow users to select files by file name rather than thumbnails

## How Has This Been Tested?
Tested in the local environment

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I found a few issues.
1. Radio buttons on Weather F/C settings are no longer appearing, probably a styling issue.
2. Per mockups, a long filename should use ellipsis. Instead, it is taking two lines and looks misaligned.
3. Padding top&bottom on each file should be 10px, it is at 20px.

Thanks

**Comment by alex-deaconu** [comment]
@ezequielc I've worked to address all your review items.

To confirm, the height of each Storage list item height is now 39px +1 px top border from previous element. Also, folder rows were not as tall because of the missing checkbox. I've added padding to account for that so all rows should be the same height.

In addition, I've fixed ellipsis for the folder name when navigating to a folder with a long name.

Please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good 👍

**Pull request merged**
