### PR TITLE
Implemented Image/Video types filter

### PR DESCRIPTION
**Pull request by alex-deaconu**
[stage-4]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good. 👍
Just wondering, did you consider using content type instead of file extension for filtering? Do you think it would help? Cheers

**Comment by alex-deaconu** [comment]
@ezequielc good question. I did actually however I opted for this particular implementation.

Reasons? Well, actually I didn't know if the content-type header was reliable, ie. I thought it was based on the extension. However, double checking the code it seems that header is not arbitrarily set, but actually obtained from the file object in the browser (https://github.com/Rise-Vision/rise-vision-apps/blob/master/web/scripts/storage/services/svc-upload-uri.js#L32)...

Having said that, I agree it would be a more reliable method for filtering the files, in case someone gets their extensions mixed up. Do you think I should update?

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I don't think it is worth the effort right now. In the future, if we have problems we can revisit the code. 👍 Cheers!

**Comment by alex-deaconu** [comment]
@ezequielc sounds good. Thanks.

**Pull request merged**
