### PR TITLE
Toggle license locally or remote

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Toggle license locally or remote

Based on new or manage display modes
Toggle is common in directive

Move other functionality to directive
Deprecate unlock display feature modal
Fix redirect after add

[stage-18]

## Motivation and Context
When adding a display we cannot toggle the license on the server, so we do a local toggle.

## How Has This Been Tested?
Tested changes locally. Will update tests in a subsequent PR.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I noticed that when I have 0 licenses available and I toggle off a licensed display, it is showing the popup to purchase additional licenses. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc the issue you described should now be fixed. Wondering if you could double check. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Dpuble checked and looks good 👍 Thanks!

**Pull request merged**
