### PR TITLE
Remove shipping address from purchase flow

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Remove shipping address from purchase flow

Use selected company for purchase
Update company shipping address with billing

[stage-19]

## Motivation and Context
Billing Friction epic

## How Has This Been Tested?
Updated unit tests. Tested locally. Updated e2e tests.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I could not finish a checkout process. When I click Pay Now button, it shows a generic error in the UI, and in Store logs it shows `User must belong to the billing company`. We will probably need to do some server side work here. Thanks

**Comment by ezequielc** [comment]
@alex-deaconu And I found the same error when trying to enter credit card details. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc I will take a look, thanks!

**Comment by alex-deaconu** [comment]
@ezequielc I've removed the condition for this in the store-server via https://github.com/Rise-Vision/store-server/pull/1145 and it should be working correctly now. I tested locally but I would like to do a bit more testing before requesting review for the store-server PR. Just a heads up if you want to retry this. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Thanks for the heads up. I will review it and test tomorrow morning.

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Looks good 👍

**Pull request merged**
