### PR TITLE
Update financial license message and link

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Include description for a 30 day trial

[stage-18]

## Motivation and Context
Hopefully improve adoption of Financial Content

## How Has This Been Tested?
Updated unit tests, validated manually in the local environment

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review, thanks!

**Comment by sheadarlison** [comment]
@ezequielc @alex-deaconu That was fast! Feel free to ship on Monday. Thanks

**Comment by alex-deaconu** [comment]
@sheadarlison @ezequielc this has been released. Thanks!

**Comment by sheadarlison** [comment]
Thanks @alex-deaconu !

**Pull request merged**
