### PR TITLE
Fix #280 - Apps not detecting installed display

### LINKED ISSUE #280: Displays App Bug
On this page it says the display is online: https://apps.risevision.com/displays/list?cid=2c173532-d5d2-4642-9197-f7078dd8dd7a

And when you click the display it says the player isn't installed https://apps.risevision.com/displays/details/F7PAAKJS3KYX?cid=2c173532-d5d2-4642-9197-f7078dd8dd7a

Screenconnect session is here, it's the one titled Peter's Display https://connect.risevision.com/Host#Support/All%20Sessions//e1a06563-f222-4eac-9954-5933e82b1918 

displays-issue

If you have any questions please tag me in Hipchat or on the card. Thanks!

### PR DESCRIPTION
**Pull request by ezequielc**

### CODE REVIEW

**Comment by ezequielc** [comment]
- Rely on `playerVersion` insted of `lastActivityDate` to know if a Display has a Player installed

Sample display: https://apps-stage-0.risevision.com/displays/details/BFGU948RZVBU

@Rise-Vision/apps Please review. Thanks

**Comment by ezequielc** [comment]
@Rise-Vision/apps There are some users complaining about this issue, so I would like to release as soon as possible. Could someone take a quick look here? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc wondering if it's possible to show a similar Red status in the Displays List? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Thanks, I will work on the API response. Cheers

**Comment by ezequielc** [comment]
@alex-deaconu If ok with you, I will release this while I work on API, so we can solve the main issue for the users. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc I agree releasing this is a good idea. Thanks!

**Pull request merged**
