### PR TITLE
fix css issues [stage-4]

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@ezequielc @alex-deaconu @settinghead 
Please review
https://apps-stage-4.risevision.com/

**Comment by ezequielc** [comment]
@ghislaineguerin 👍

**Comment by settinghead** [comment]
@ghislaineguerin :+1:

**Comment by alex-deaconu** [comment]
@ghislaineguerin 👍 . Wondering if you can squash too - noticed they have a new `Squash and Merge` option so it shouldn't be a hassle. Thanks!

**Pull request merged**
