### PR TITLE
Fix playlist-container view item heights [stage-8]

### PR DESCRIPTION
**Pull request by stulees**
## Description
Stying revisions to be consistent in different views and ensure correct view item height calculating.

## Motivation and Context
Fixes first two items in checklist of this card - https://trello.com/c/Zv0YbfzF/7581-meet-ui-specs-3

## How Has This Been Tested?
Locally and on staging-4:

https://apps-stage-8.risevision.com/templates/edit/c27830e2-b426-42fb-afcc-901de06c6955/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
n/a

### CODE REVIEW

**Comment by stulees** [comment]
@olegrise Please review, thanks!

**Comment by olegrise** [comment]
@stulees it seems that [this use case](https://app.abstract.com/share/422f0953-788a-48b2-bf55-06880a27fcd3?collectionId=1eba19f7-14c3-492f-9e7c-7488289cf2e1&collectionLayerId=77c0bdc8-d941-46f8-94dd-1e9099a3935e&present=true&preview=false&sha=c89d1ef5d90f61311b6a8e72a8a1f4ab7770a461) is not rendered correctly.

**Comment by stulees** [comment]
@olegrise Hm I see that now, these fixes were focused on their being selected templates already. I'll look at fixing this up now, thanks!

**Comment by olegrise** [comment]
@stulees just noticed that the Add Template button is few pixels higher that the bottom of the preview. 
Screen Shot 2020-04-07 at 11 19 03 AM

**Comment by stulees** [comment]
@olegrise Should be good now, please review again, thanks

**Pull request merged**
