### PR TITLE
Fix/table classes 3

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@RV-Adrian staging looks good, no issues 👍 . Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian one issue I discovered while looking around:
https://screencast.com/t/LoGuCs9V

This happens with the Widget in the Presentation, when the Subscription status is blank: https://apps-stage-4.risevision.com/editor/workspace/e81d74d4-063e-4b08-9195-cff3bb045dfe/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

Thanks.

**Comment by alex-deaconu** [comment]
@RV-Adrian regarding the issue above, if @ezequielc agrees I think we can release without fixing it. It's related to Widgets that were not added from the Store, so for most clients it should not occur. My suggestion is we fix it with a subsequent release. Thoughts? Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu I think that makes sense. It looks like the `.trial` class is applied which is giving it an appearance based on status. Seems it's a bug?

**Comment by ezequielc** [comment]
@alex-deaconu @RV-Adrian I agree, we can add a card and fix it next. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu @fjvallarino 
Tagged Common Style and Components, and now staged at https://apps-stage-4.risevision.com

Checklist:
Presentations list
Shared Templates list
Schedule Detail > Distribution selector
Schedule Detail > Playlist > Add Presentation
Displays list
Storage > List view
Editor > Add Image > Storage > List view
Editor > Placeholder > Distribution selector
Alerts > Distribution selector + Add Presentation

**Comment by alex-deaconu** [comment]
@RV-Adrian everything looks good on my part 👍 . I would suggest waiting for 1 more reviewer's comments before merging. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Sounds good, thanks!

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
