### PR TITLE
Handle closing of date and time picker popups on iOS

### PR DESCRIPTION
**Pull request by fjvallarino**
## Description
Handles events to close date and time pickers on iOS when touching outside the popup. 

## Motivation and Context
This worked correctly both on Desktop and Android, but not on iOS.

The solution for the Date picker is not really clean. Ideally we would fork the original repository (https://github.com/angular-ui/bootstrap) and apply the change in our own copy but, checking the version we reference in `bower.json`, we're not using latest. I almost went this route, but I'm afraid we may introduce unexpected issues.

## How Has This Been Tested?
It can be validated here: https://apps-stage-7.risevision.com/templates/edit/b52abde6-951e-4d17-9c06-f91a8888e827/?cid=87977ab8-38b6-47fb-ad5e-256b8cc4b46d.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

@stulees please review

### CODE REVIEW

**Comment by stulees** [comment]
@fjvallarino Given our discussion this morning, should these changes be modified to just handling time picker only for now?

**Comment by fjvallarino** [comment]
@stulees not sure. Maybe adding a comment saying this is temporary, and later remove it, would be a good option?

**Comment by stulees** [comment]
@fjvallarino I assume risk is low in keeping the code despite date picker handling not working on iOS, can you confirm?

**Comment by fjvallarino** [comment]
@stulees the code is restricted to the Counter component and it does not affect other date pickers (e.g., the one in Schedules). But this version does work on iOS for the date picker too!

**Comment by stulees** [comment]
@fjvallarino Ah okay I misunderstood, I see now the cleaner version is what we've deferred to our post release period. I've tested your validation link and looks good! 👍

**Pull request merged**
