### PR TITLE
Feature/apps launcher experiment

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu 
Can you take a look and let me know your thoughts and how we can proceed from here?
Also, I assume there's a better way to link to the video, image and blank templates?

Thanks!

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@alex-deaconu I have added your suggestions. Please take a look. thanks

**Comment by alex-deaconu** [comment]
Been working with @ghislaineguerin to fix this integration. Basically, we are setting a flag in Optimizely on the $rootScope and inside the partial we are checking that flag. 

The Optimizely script is quite simple:

```
var $rootScope = angular.element(document.body).injector().get('$rootScope');

$rootScope.presentationTemplateCtaExperiment = true;
```

and as you can see in the code we just use an `ng-if` to select which div to show.

Staging link:
https://apps-stage-4.risevision.com/?optimizely_x8290831837=1&cid=34bc012f-bb3a-4005-9744-27df580ee636

@ezequielc @fjvallarino please review the above. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu @ghislaineguerin is there anything special I should be doing to get the alternative page? I tried a bunch of times in Incognito mode (closing the window, not closing it, any combination) and I got the regular "How Simple is Rise Vision?" every time.

**Comment by ghislaineguerin** [comment]
@fjvallarino I see the variation, could you try refreshing many times? or appending this parameter 
optimizely_token=PUBLIC

**Comment by ezequielc** [comment]
@ghislaineguerin @alex-deaconu I can see both versions. Looks good. Thanks! 👍

**Pull request merged**
