### PR TITLE
Only use fallback when browser is Firefox

### PR DESCRIPTION
**Pull request by fjvallarino**
This version only uses fallback when the browser is Firefox, to avoid ghosting issues. Since this causes Firefox to present the ghosting problem, a style was added here as a workaround: https://github.com/Rise-Vision/common-header/pull/817

Regarding the browser detection part, I kept it as simple as possible (maybe too simple, actually); I'm not sure if we have a common module we can use for this kind of functions. The obvious alternative is using something like https://www.npmjs.com/package/detect-browser, but I'm not sure we actually need it.

This is deployed on stage-1.

@Rise-Vision/apps please review

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino the simple Firefox check works for me. If we need it elsewhere we can add a utility function. Looks good 👍 . Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu @RV-Adrian fix for Firefox should work fine on both Presentations and Schedules now

**Comment by RV-Adrian** [comment]
@fjvallarino Looks good! The only thing I noted is on Firefox in mobile view, I was not able to move any playlist items (not a ghosting issue, just didn't move at all?) If we decided not to support that then 👍

**Comment by fjvallarino** [comment]
@RV-Adrian mmm, I don't think we support Firefox mobile. I'm merging for the moment

**Pull request merged**
