### PR TITLE
handle enter key [stage-9]

### PR DESCRIPTION
**Pull request by santiagonoguez**
## Description
Handle enter on failsafe input on bulk delete confirmation modal.
Automated tests will be created in next PR.

[stage-9]

## Motivation and Context
Issue 2252

## How Has This Been Tested?
Fix working on stage-9.
Automated tests will be created in next PR.

## Release Plan:
Won't be released until automated tests are created.

- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No need for documentation update

### CODE REVIEW

**Comment by ezequielc** [comment]
@santiagonoguez I am wondering if you tried to use the `ng-submit` pattern, similar to https://github.com/Rise-Vision/rise-vision-apps/blob/298f1ef835dd160f0617c240b7969e8450a2c60c/web/partials/components/scrolling-list/bulk-edit-modal.html#L1. I think it provides a cleaner solution. Thanks

**Comment by santiagonoguez** [comment]
@ezequielc sounds good, I'll do that ! thanks :D

**Comment by santiagonoguez** [comment]
@ezequielc @alex-deaconu I've implemented the submit based solution. Much cleaner indeed, thanks Ezequiel ! 

Please review again.

**Comment by ezequielc** [comment]
@santiagonoguez Looks good, thanks for updating it!

**Review by alex-deaconu — APPROVED** [review]
@santiagonoguez nice 👍

**Pull request merged**
