### PR TITLE
Render clock, html, Calendar and Spreasheet widgets

### PR DESCRIPTION
**Pull request by alex-deaconu**
[stage-3]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
I've created a Sample Presentation showcasing all the rendered Widgets:
https://apps-stage-3.risevision.com/editor/workspace/0f7eae66-f3df-497c-9d38-f462fdfde09d/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

Also, to note, I did not add any staging IDs for Calendar & Spreadsheet widgets as the products are not set up on staging.

@ezequielc @fjvallarino @RV-Adrian please review. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Nice! On first load, I got a 'Failed To Load Presentation' error but it only happened once.

For the HTML Widget: I was curious to see how a more complex page would appear, but I couldn't access the Widget settings. I guess this is due to the stage?

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Comment by alex-deaconu** [comment]
@RV-Adrian good catch. I just updated the PR to include the test versions of the Spreadsheet & Calendar widgets. Also ran the API endpoint for associating the HTML, Spreadsheet & Calendar widgets on the test server with their corresponding Product Codes.

What this means is now you can add a new HTML, Spreadsheet (also updated to 2.0) or Calendar widget to your presentations on the test server for testing. I've also updated the Presentation above to use the test versions of the widgets. 

Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Great, works well 👍

**Pull request merged**
