### PR TITLE
Sort Display List by any column

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Sort Display List by any column

## Motivation and Context
Network Management epic

## How Has This Been Tested?
Tested locally and on [stage-13].
Identified 2 sorting defects that were fixed in Core and validated.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by ezequielc** [comment]
Note: e2e_displays failed due to https://github.com/Rise-Vision/core/issues/804
PR also blocked on https://github.com/Rise-Vision/core/issues/803.

**Review by alex-deaconu — APPROVED** [review]
Just a thought, I'm wondering if it's too late to split this PR into the refactoring part for `onlineStatus` which can be released, and the actual sort implementation which is blocked on the issues. Thoughts?

@ezequielc otherwise, looks good. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu At this point previous sorting issues are resolved. We are blocked on `onlineStatus` discrepancies (https://github.com/Rise-Vision/core/issues/810) and while it is not resolved, we can't release as status would be incorrect as well as sorting by status. So I would prefer to wait for now. If the issue takes long to be resolved, we can revisit this an try to split it. Thanks

**Comment by ezequielc** [comment]
@alex-deaconu As discussed, I will stop combining Messaging Service and Core API statuses/lastConnection before merging this PR. Thanks

**Review by alex-deaconu — APPROVED** [review]
@ezequielc looks good 👍

**Pull request merged**
