### PR TITLE
Create separate loader service for oidc

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Create separate loader service for oidc

[stage-19]

## Motivation and Context
Separate loader for the library object

## How Has This Been Tested?
Tested changes locally.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc @santiagonoguez please review. Thanks!

**Review by ezequielc — COMMENTED** [review]
@alex-deaconu Code looks good, but I am not sure I follow why we need this change. There are no asynchronous requests, so I don't see the need of a promise. Is it for consistency with other loaders? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc good point, I did model this after other loaders but you're right we don't need a promise. I will fix. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc @santiagonoguez based on our chat, I've updated the loader code to reject the promise if the `Oidc` object is not present.

I also had to merge the main branch into this one, which created some conflicts around the tracking code.

Please review the latest commit. Thanks.

**Review by santiagonoguez — APPROVED** [review]
@alex-deaconu looks good to me, thanks !

**Pull request merged**
