### PR TITLE
Update CS to fix Playlist height

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc @RV-Adrian the issue is not completely fixed. When in a Sub-Company the last placeholder is only shown half way, if that Company is also a Test Company, the Placeholder is completely hidden: http://screencast.com/t/NYqvXoBL2sSa. Thanks.

**Comment by ezequielc** [comment]
Good catch @alex-deaconu . @RV-Adrian Could you take a look? Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc 
I wasn't able to recreate this. With the two banners I could still get to them bottom of the list. GIF attached. See anything I'm missing?
bug2

**Comment by ezequielc** [comment]
@RV-Adrian Are you running the staged version (stage-0)? Thanks

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu Yes, tried it locally and stage-0. Nothing was cut off. Wondering if it's due to browser or OS...

**Comment by ezequielc** [comment]
@RV-Adrian @alex-deaconu Please review. It looks good to me. If all ok, we can tag CS and I will squash here. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc @RV-Adrian looks good. Thanks for fixing! 👍

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu 
👍 
Tag at https://github.com/Rise-Vision/common-style/releases/tag/v1.3.79

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc 
👍

**Pull request merged**
