### PR TITLE
Migrate file-entry and empty-file-list

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Migrate file-entry and empty-file-list

[stage-2]

## Motivation and Context
Angular migration epic.

## How Has This Been Tested?
Tested locally.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I am seeing some errors when trying to drag images to reorder:
Screen Shot 2021-07-19 at 6 05 35 PM

Sample presentation: https://apps-stage-2.risevision.com/templates/edit/5421b702-c852-4f2a-88a6-b1a6c1c99968/?cid=554d3ef9-78b7-4726-8f46-c1ec140c166d
They are not happening on stage-0. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc interesting. It is related to the `replace: true` option on the original `file-entry` directive. Looks like the `parentElement > component > div` chain is unexpected. It should be `parentElement > div` for the drag element `class="rv-sortable-item"`. I will take a look at potential options for fixing. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc my latest commit should fix the drag issues, as per the description above. Also, I'm trying to correct a failing e2e test with financial. Thanks.

**Review by ezequielc — APPROVED** [review]

**Pull request merged**
