### PR TITLE
Drag & Drop reorder for schedule items [stage-2]

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @fjvallarino  @ezequielc 
Common Style reviewed and merged. Updated the branch, and this is staged on https://apps-stage-2.risevision.com/
Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian looks good. @ezequielc wondering if you could do a quick review. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc Please review the code portions from @alex-deaconu 
Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good.
@RV-Adrian The empty message is anchoring to the bottom. Is it intentional? 
screen shot 2017-05-15 at 6 10 21 pm

Thanks

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu 
Looks like that element fell out of the scrollable-list. 
Good catch, should be okay now. Thanks!
https://apps-stage-2.risevision.com/

**Comment by ezequielc** [comment]
@RV-Adrian @alex-deaconu 👍

**Comment by alex-deaconu** [comment]
@RV-Adrian 👍 thanks for fixing!

**Pull request merged**
