### PR TITLE
Bulk delete schedules

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Bulk delete schedules

[stage-2]

## Motivation and Context
Network management epic.

## How Has This Been Tested?
Tested changes locally; updated unit tests.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good 👍  There is one minor issue, probably from the previous PR. In the progress panel, it doesn't show the 'schedule' word. Thanks
Screen Shot 2020-10-06 at 11 38 51 AM

**Comment by alex-deaconu** [comment]
@ezequielc good catch! I am just fixing that in a separate PR coming up. Thanks.

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Sounds good. Thanks!

**Pull request merged**
