### PR TITLE
Endpoint for Send Us a Note

### PR DESCRIPTION
**Pull request by ezequielc**
We need an endpoint for Send Us a Note too. 
Stage link: https://apps-stage-0.risevision.com/send-note

@olegrise Please review. Code is similar to previous PR. Thanks!

### CODE REVIEW

**Comment by olegrise** [comment]
@ezequielc is https://apps-stage-0.risevision.com/send-note suppose to show "send a note" popup?

**Comment by ezequielc** [comment]
@olegrise Yes, it should. I think someone did another build, I will use another stage link. I will share once build is done. Sorry about that. Thanks

**Comment by ezequielc** [comment]
@olegrise Updated stage link: https://apps-stage-1.risevision.com/send-note . Please review, thank you!

**Comment by olegrise** [comment]
👍

**Pull request merged**
