### PR TITLE
Onboarding slider

### PR DESCRIPTION
**Pull request by alex-deaconu**
Hiding Launcher bar

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I am not strong on this, but I think the original idea was to show directly the last slide if I come back to the Home page after seeing all slides. @ghislaineguerin Any thoughts on this? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc I did not find any release notes or discussions describing this functionality. I just went with it based on this document (https://docs.google.com/document/d/1SQqfYBj0QDjzyY1SVJxggbmLrROc0m18yprQnbxwa5M/edit) so any additional details for the implementation may have been missed. Thanks.

**Comment by ghislaineguerin** [comment]
@ezequielc yes, that is the intended functionality.

**Comment by ezequielc** [comment]
@ghislaineguerin @alex-deaconu Would be ok to release as is and add this conditional later? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino @ghislaineguerin updated logic to show the last page for returning users, as discussed. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good! Thanks for implementing it!

**Pull request merged**
