### PR TITLE
Show first item name if Placeholder is not rendered

### PR DESCRIPTION
**Pull request by alex-deaconu**
[stage-2]

@Rise-Vision/apps please review. Thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Wasn't this change supposed to include the "bonus" to show the resize circles? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc oh, you're right. Not sure what happened there, @RV-Adrian any ideas how we can add those circles to the Placeholder? Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu 
That's weird, will look into it this morning.

PS. Can I be added to the Rise-Vision/Apps tag used above? Thx!

**Comment by RV-Adrian** [comment]
@alex-deaconu 
From what I remember, I had to push a new release without the dots because of some conflict. Can you stage with v1.4.25? Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian okay, staging new version. Also, added you to the group. Thanks.

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps as per the comment above, the re-size dots for the Placeholder are now showing. Please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu @RV-Adrian  Looks great 👍 Thanks

**Pull request merged**
