### PR TITLE
Fix issue #68 User gets booted back to master company after clicking …

### PR DESCRIPTION
**Pull request by ezequielc**
…"Save" on Display page

@RV-Adrian Please review. Thanks!

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ezequielc Woops, sorry for merging those disabled tests!

Looks good, although I should mention the above happens for me when I enter the 'Display Details' view as well.

**Comment by ezequielc** [comment]
@RV-Adrian Does it still happen when entering Display Details (stage-0)? It should be fixed. Thanks

**Comment by ezequielc** [comment]
Sorry @RV-Adrian. Build wasn't finished. You can try it now: https://apps-stage-0.risevision.com
Thanks

**Comment by RV-Adrian** [comment]
@ezequielc All good!

**Comment by ezequielc** [comment]
Thanks @RV-Adrian !

**Pull request merged**
