### PR TITLE
Center new placeholders

### PR DESCRIPTION
**Pull request by alex-deaconu**
Take scroll into consideration
Note: Offsets are based on current css values

JShint fixes

[stage-4]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good. Just one question about functionality. I had the impression we were going to fix the case where placeholders were added on top of each other when creating multiples placeholders. We would add an offset every time we create a new placeholder. Is this another card? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc hmm, ok. I guess I missed that; will try to revisit. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think you should confirm in the card, maybe I am wrong. Cheers

**Comment by alex-deaconu** [comment]
@ezequielc discussed on the card and during standup. I will add a `20px` offset as suggested so Placeholders don't overlap. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Looks good 👍 Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc thanks!

**Pull request merged**
