### PR TITLE
Feature/attributes list UI

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Attributes list UI improvements 

- Match mockups
- Change Playlist icon
- Add Schedule icon
- Remove .attribute-edit

## Motivation and Context
Playlist UI

## How Has This Been Tested?
Locally and on [stage-1]

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc I just noticed the Schedules, Colors and Brand Settings rows do not highlight on hover in the list, while other components do. I'm not actually sure the hover is desirable in the first place. Thanks.

**Review by alex-deaconu — APPROVED** [review]
👍

**Comment by ezequielc** [comment]
@alex-deaconu From my understanding, components highlight in the list to match their highlight in the preview area. Colors, Branding and Schedules don't have a specific component to highlight in preview, that is why the don't highlight on hover. Basically, I followed what was in place, just fixed Schedule to match that logic. But I may be wrong :) Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc oh... I was not aware that was the behaviour. Sounds good in that case. Thanks!

**Pull request merged**
