### PR TITLE
Fix/sticky mobile nav

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
Pull Request for https://trello.com/c/YOxAnegR/2233-issue-673-user-nav-is-not-sticky-and-scrolls-off-screen-1
Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian looks much better. Thanks for fixing 👍 .

**Comment by alex-deaconu** [comment]
@RV-Adrian this PR is no longer needed. https://github.com/Rise-Vision/rise-vision-apps/pull/410 was merged which deploys a later version of Common-style. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Thx!

**Pull request closed without merging**
