### PR TITLE
Update Publish and Restore behavior

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good. Couple of things I just noticed:
A brand new, blank Presentation has the `Save` button disabled until I make a change.
When making a change on a Published Presentation, the `Restore` button is enabled. At this point making a server trip to Restore is useless (since the user hasn't saved), so maybe we should disable it?

Neither are major points, just raising for discussion.

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I think Restore action is ok, because it will replace the unsaved content in the editor with the Published version.
About Save, we could let it always enabled for a new Presentation. @RV-Adrian Thoughts? Thanks

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu 
If it's extra work to enable Save for an un-modified Blank Presentation, I say leave it.
Why would they want to save something completely empty? Same could even be said for an un-modified Template I think.

**Comment by ezequielc** [comment]
Thanks @RV-Adrian. It is not a lot of work, but it is extra work, including tests, etc.
@alex-deaconu If you agree, I think we are good to merge. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc agreed. 👍 . Thanks.

**Pull request merged**
