### PR TITLE
Build results & manual lint fixes

### PR DESCRIPTION
**Pull request by alex-deaconu**
Fix a failing e2e test

@ezequielc @fjvallarino please review. Thanks!

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Comment by ezequielc** [comment]
@alex-deaconu @fjvallarino FYI, I am not sure if you are aware, but adding ?w=1 to the diff url ignores the whitespaces (https://github.com/tiimgreen/github-cheat-sheet#ignore-whitespace) Very useful this time 😃

**Comment by alex-deaconu** [comment]
@ezequielc great tip, thanks!

**Comment by fjvallarino** [comment]
@ezequielc wow, that's really useful! :D

**Pull request merged**
