### PR TITLE
use local storage for oidc session [stage-9]

### PR DESCRIPTION
**Pull request by santiagonoguez**
## Description
Use localStorage for OIDC.

[stage-9]

## Motivation and Context
So it works across tabs.

## How Has This Been Tested?
Works nice for multiple tabs under stage-9, for both login and logout.

## Release Plan:
Part of prototype

- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by santiagonoguez** [comment]
@alex-deaconu @ezequielc a question here is if I also be touching UserManager configuration here: https://github.com/Rise-Vision/rise-vision-apps/blob/fix/google-auth/web/scripts/user-manager-silent.js#L10

but I realize there's no settings object there, and maybe that's part of the work that Ezequiel is doing, so I didn't touch it for the time being :O

**Comment by alex-deaconu** [comment]
@santiagonoguez I believe the silent callback already uses local storage by default. Also, curious what are the other storage options, if any? Thanks.

**Review by alex-deaconu — APPROVED** [review]
Works perfectly, thanks for addressing!

**Comment by santiagonoguez** [comment]
@alex-deaconu I don't see other storage options in their main project; I've just started looking if they have additional repos with extensions for this. If not, I guess what's needed is to implement their store contract: https://github.com/IdentityModel/oidc-client-js/blob/dev/src/WebStorageStateStore.js

**Pull request merged**
