### PR TITLE
Migrate image component

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Migrate image component

[stage-2]

## Motivation and Context
Angular migration epic.

## How Has This Been Tested?
Tested locally.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc there were some issues with the wording for the Empty File List which I had to correct, but it broke the build. So I pushed another commit to fix that and simplify the whole thing. This should be ready for review now. Thanks!

**Review by ezequielc — COMMENTED** [review]
@alex-deaconu Code looks good but I found an issue. The 'Design With Canva' feature is failing to start uploading the design once saved in Canva. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc thanks, I will take a look.

**Comment by alex-deaconu** [comment]
@ezequielc looks like it was a copy paste issue from video, the image specific attribute got lost. Added it back, please see the last commit. Thanks!

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Great! Looks good 👍

**Pull request merged**
