### PR TITLE
Fix issue with Storage sorting

### PR DESCRIPTION
**Pull request by alex-deaconu**
Most likely caused by the refactoring and mixed up scopes
Refactored search to match other lists and used scope function for sort

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fix for #403 

@ezequielc @fjvallarino please review. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu looks good. The only concern is it breaks the fix (hack?) we added for the correct ordering of duplicates.

**Comment by alex-deaconu** [comment]
@fjvallarino it should not, does it? It should be using the same filter function as before... Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu sorry, it works fine. I don't know what I saw.

:+1:

**Pull request merged**
