### PR TITLE
Store selected directive object rather than selector

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Store selected directive object rather than selector

Allows using various other attributes from the
directive

[stage-12]

## Motivation and Context
Component navigation refactoring

## How Has This Been Tested?
Tested changes locally. Will update unit tests and make further improvements in subsequent PRs.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc initial PR for this. Please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I noticed that the title becomes inconsistent after I navigate back and forth a few times between logo and colors on Branding settings. I couldn't replicate, but title was incorrect for root Logo component after doing that. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc thanks, I will take a look.

**Comment by alex-deaconu** [comment]
@ezequielc the issue is now fixed and this is ready for release. Thanks.

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Looks good. Thanks for fixing it 👍

**Pull request merged**
