### PR TITLE
Feature/svg in image grid

### PR DESCRIPTION
**Pull request by santiagonoguez**
This displays the real image for SVG instead of a generic one.

Validation: https://apps-stage-9.risevision.com/templates/edit/d4a5a9c7-2cc7-4f99-87cf-1e8457d0ea9a?cid=cf85e5c4-9439-40ce-94d6-e5ea6ea2411c

The image that says 'display control' on the right column has SVG format.

### CODE REVIEW

**Comment by fjvallarino** [comment]
@santiagonoguez if after selecting the SVG file I try to add it to the list, I get the following error:

```
dependencies.js:23410 TypeError: Cannot read property 'thumbnail' of undefined
    at u (dtv-component-image.js:51)
    at dtv-component-image.js:42
    at Array.forEach (<anonymous>)
    at c (dtv-component-image.js:41)
    at Object.addSelectedItems (dtv-component-image.js:27)
    at h.r.addSelected (dtv-basic-storage-selector.js:111)
    at fn (eval at compile (dependencies.js:24337), <anonymous>:4:224)
    at t (dependencies.js:25424)
    at i (dependencies.js:35803)
    at h.$eval (dependencies.js:27205)
```

**Comment by santiagonoguez** [comment]
@fjvallarino  thanks, I'll check :D

**Comment by stulees** [comment]
@santiagonoguez Not sure if you're still working on the fix from @fjvallarino previous comment, but this is what I see when I try adding that SVG image to the list. 

image

**Comment by santiagonoguez** [comment]
@fjvallarino it's fixed now, thanks !

**Comment by santiagonoguez** [comment]
@stulees so, it's not displaying thumbnail, that's another issue, I'll check, thanks !

**Pull request merged**
