### PR TITLE
Remove bower common-i18n branch [stage-1]

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu 
See above for removing the common-i18n branch call.  Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu 
I made this update on the 'video experiment' branch as well and it looks like it closed this PR automatically. Sorry about that! Will tag you on the validation for that one shortly.

**Comment by alex-deaconu** [comment]
@RV-Adrian I think that's fine. As long as the tag is removed with the other PR, I don't think we need this. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Perfect, deleting branch now

**Pull request closed without merging**
