### PR TITLE
Reuse Share button directive from Apps Home in Schedule Details 

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Adds Share button directive in Schedule Details.
Uses type button to prevent submit/save on Schedule Details.
Adds button-class to the directive to customize class on Schedule Details (default vs primary button).
Updates E2E tests.
Removes code related to old Shared Schedule Modal.

## Motivation and Context
Schedules improvements epic.

## How Has This Been Tested?
Manually tested locally and on stage-1.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Please review. It may be easier to review each commit individually. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Yeah, good catch. I will add it as a new PR on top of this. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I double checked and the modal is working as expected ([sample](http://localhost:8000/schedules/details/484b5e14-7a03-4362-980b-3a1d57a0aa47?cid=edc26bd2-4b4a-49cc-b2b1-840e6ba9bd51)). 
It is implemented as part of toggling the popover: https://github.com/Rise-Vision/rise-vision-apps/blob/ce24deb3f89018c789dbe5033ed26391515b6937/web/scripts/schedules/directives/dtv-share-schedule-button.js#L32-L35

So I think we are good here. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc oh, missed that. Thanks for confirming!

**Pull request merged**
