### PR TITLE
CH Update: fix script that automatically hides extra zendesk widget fields

### PR DESCRIPTION
**Pull request by settinghead**
- Rename common-header to rise-vision-common-header for easier bower link ops

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@settinghead as the repo name is `common-header`, I don't think we should change the folder name here. If you want to fix bower link you can do so in the common-header repo.

Also, the build will most likely not pass at this point. There's another PR being reviewed which should fix the failing e2e tests.

Thanks.

**Comment by settinghead** [comment]
@alex-deaconu ok makes sense re. changing CH name. I'll update the name in CH when an opportunity arises later. Thanks for the heads up

**Comment by alex-deaconu** [comment]
@settinghead FYI Apps build should be fixed now. Thanks!

**Comment by settinghead** [comment]
@alex-deaconu great! Thanks for the update.

**Pull request merged**
