### PR TITLE
Unit tests for updating po number

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Unit tests for updating po number

[stage-19]

## Motivation and Context
Fix unit test coverage.

## How Has This Been Tested?
Tests pass.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Also removed clearing the poNumber variable on Cancel.

@ezequielc @santiagonoguez please review. Thanks!

**Review by santiagonoguez — COMMENTED** [review]
@alex-deaconu I updated the PO, then clicked edit again and in the input field I see empty field. If I close I see the updated PO though. Is this behavior expected at this point ?

https://apps-stage-19.risevision.com/billing/invoice/6806?token=estKey&cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

**Comment by alex-deaconu** [comment]
@santiagonoguez will take a look and fix. Thanks!

**Comment by santiagonoguez** [comment]
@alex-deaconu I also can't reproduce what I previously saw :O so I agree we shouldn't spend more time on that, thanks !

**Comment by alex-deaconu** [comment]
@santiagonoguez sounds good, thanks for taking another look. If we find an issue we can fix at a later date. Thanks!

**Pull request merged**
