### PR TITLE
Update common-e2e dependencies

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Update common-e2e dependencies

## Motivation and Context
Keep dependencies up to date and resolve security vulnerabilities for rv-common-e2e

## How Has This Been Tested?
No actual functionality or build updates
Tested locally and on Circle CI that the build passes

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
For https://github.com/Rise-Vision/rv-common-e2e/pull/55.

@ezequielc please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc FYI, actually, outside of the commit for rv-common-e2e, no other dependencies are updated by this PR in `package-lock.json`. ie. Apps doesn't use any rv-common-e2e dependecies. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Ok, so do we need to merge this or should we close it? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc I'm not sure. I don't know if CCI uses the `package-lock.json` versions or just gets the latest from npm when we do `npm install`.

However, I did get an error when I had a deleted branch name in package-lock when doing npm install.

I will merge for consistency however, otherwise the next package-lock update would include this change and may cause confusion.

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Ok, makes sense 👍 Thanks!

**Pull request merged**
