### PR TITLE
Fix logic for missing product

### PR DESCRIPTION
**Pull request by alex-deaconu**
Instead of removing product,
Assume product is missing,
And add it when subscribed

Ensure search query is applied

Fix replace issue in Add User email (https://github.com/Rise-Vision/common-header/pull/793)

[stage-3]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc the object currently contains the full API response for that Product. To be honest, I didn't know which fields are needed and being used, so it was more or less a trial and error process. Will remove the extra lines as it doesn't seem those are being used. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Sounds good. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc updated and also pushed some apparently overdue Formatting and JSHint fixes. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Pull request merged**
