### PR TITLE
Fix users list; upgrade Angular to v1.5.11

### PR DESCRIPTION
**Pull request by alex-deaconu**
CH update from this PR: https://github.com/Rise-Vision/common-header/pull/657

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fixes #336 . Also upgrades Angular JS version.

@Rise-Vision/apps please review. Thanks!

**Comment by fjvallarino** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@fjvallarino the unit tests were failing consistently on 

```
 controller: display details requestScreenshot should request a screenshot successfully
``` 

so I did a bit of refactoring. Please review. Thanks!

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
