### PR TITLE
Chore/e2e unauthenticated invoice access

### PR DESCRIPTION
**Pull request by santiagonoguez**
## Description
Adds E2E tests to invoice page. 

Similar, access to unpaid invoices pages will be implemented in next PR.

## Motivation and Context
E2E coverage for unauthenticated access.

## How Has This Been Tested?
This is a test.

## Release Plan:
No runtime changes.

- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by ezequielc** [comment]
@santiagonoguez @alex-deaconu My initial idea was to open the Unpaid Invoices list directly, without navigating to Billing, and then navigate to an unpaid invoice to test that page.
But on the other hand, we don't have any other tests covering Billing page, so I think we can use this for future tests as well, like Subscriptions list.

My main concern is about the Unpaid Invoice item in the list to move below the visible/scrollable area and the test fail in the future. But since we no longer purchase new subscriptions from this account, it should be fine. Let me know your thoughts. Thanks!

**Comment by santiagonoguez** [comment]
@ezequielc  oh, I see your point. 

What about leaving this test just before checking the existence of the unpaid invoice, so we can check the billing page. And then I create another case for the flow you were thinking of where I check both unauthenticated access using the fixed company id and token. That way the tests won't be dependent on new active subscriptions being added. Thoughts ?

**Comment by ezequielc** [comment]
@santiagonoguez I am good with your suggestion. Thanks!

**Comment by santiagonoguez** [comment]
@ezequielc I left now just the basic billing page now, please take a look.

I'll add the unauthenticated page tests as additional PRs on top of this one. Thanks !

**Review by ezequielc — APPROVED** [review]

**Pull request merged**
