### PR TITLE
Hide onboarding message after logout

### PR DESCRIPTION
**Pull request by fjvallarino**
@alex-deaconu @ezequielc this is deployed on stage-1. Not sure exactly if it is worth testing or not (it should be an e2e test)

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino I think this change needs to go in the CH. The Onboarding bar is used in Store and other Apps so the issue would appear there as well. Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu the problem is the component itself is created on Apps' index.html

**Comment by alex-deaconu** [comment]
@fjvallarino oops, you're totally right. Sorry about that. Re: test, I think a unit test can be added for this as discussed in Standup. Thanks.

**Comment by fjvallarino** [comment]
@Rise-Vision/apps updated with unit test

**Comment by alex-deaconu** [comment]
@fjvallarino looks good 👍 , thanks for fixing!

**Pull request merged**
