### PR TITLE
Implement instrument selector search functionality and UI handling

### PR DESCRIPTION
**Pull request by stulees**
- Search field UI handling
  - A search is initiated by clicking magnifying glass icon or by _Enter_ key
  - Input is cleared by clicking X icon
- Updates instrument selector list based on search results
- If results are empty, the _no results_ UI is displayed
- Whenever returning to Instruments List view, the instrument selector list is reset with most popular instruments

Validate at https://apps-stage-8.risevision.com/templates/edit/69421d64-e0a2-48f5-95df-923d501c42f8?cid=5ed8d6e8-7eac-4e88-840b-c067d16862a5

cc: @Rise-Vision/apps

### CODE REVIEW

**Comment by fjvallarino** [comment]
@stulees looks good 👍 

One minor comment: I realized, when first loading the _Financial - Currencies_ component, it takes a bit to load and meanwhile it shows a white panel. Should we be showing a spinner there?

**Comment by santiagonoguez** [comment]
@fjvallarino @stulees about the spinner, that maybe should be part of my instruments list card. If you both agree I can add it there.

**Comment by stulees** [comment]
@fjvallarino Good point, but this should be directed to https://github.com/Rise-Vision/rise-vision-apps/pull/854 as that is dealing with Instrument List, not searching. Lets move discussion there, thanks

**Comment by fjvallarino** [comment]
@santiagonoguez @stulees works for me!

**Pull request merged**
