### PR TITLE
Launcher page for Miranda

### PR DESCRIPTION
**Pull request by ezequielc**
@rodrigopavezi Could you review? Sorry for the large PR, we changed common-styles so we had to update a few html templates and related E2E tests. 

The main change here is the new Launcher, where we present the list of 10 last Presentations, Schedules and Displays.
We also added an animation explaining how Rise Vision works, which can be toggled on and off. 

Staged at: https://apps-stage-0.risevision.com/
Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc code looks good for the PR. However, I did notice an issue with the UX:
When accessing the Editor, the top of presentation is no longer accessible (http://screencast.com/t/WVwHQsd8gAt). In the production version we have some padding that may be missing here.

Also, a couple of usability issues I would like to bring up (not sure if these were discussed already):
- When clicking the “How do I show presentations and web pages?” link, the graphic shows. However, how does the user know that clicking it again hides the graphic?
- When I access the launcher page at lower (mobile) resolutions, the way the buttons/titles/lists etc are stacked seems confusing. Maybe we can add some extra spacing or dividers?

@ghislaineguerin @RV-Adrian FYI.

Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @ghislaineguerin @RV-Adrian just noticed a another issue with the Schedule Items list:
http://screencast.com/t/dlk2w1s4F. This is also occurring at apps-stage-0.risevision.com. 

Thanks!

**Comment by ghislaineguerin** [comment]
@alex-deaconu I think we need a card to fix those issues on common styles. Do you agree?

**Comment by alex-deaconu** [comment]
@ghislaineguerin agreed. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Are we good to release this PR or should we wait for the fixes? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc there are 2 styling conflicts in this version which we found; wondering if there are others we missed. I'd rather not make the call on this, @ByronDarlison thoughts? Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc sorry, I missed this, but I'm not sure what I am making the call on?  @RV-Adrian @ghislaineguerin are all styling issues fixed at this point? Thanks

**Comment by ezequielc** [comment]
@ByronDarlison In the comments @ghislaineguerin mentioned she would create a card to fix the styling issues. I am wondering whether we should wait for the fixes or if we can deploy and fix the style later. 

Issues are an extra line in Schedules Playlist (http://screencast.com/t/dlk2w1s4F) and toolbar covering top of the presentation (http://screencast.com/t/WVwHQsd8gAt). But @alex-deaconu is concerned that we may find more issues. 

Actually, I think I will do another review of the UI to be safe. Thanks

**Comment by ByronDarlison** [comment]
@ezequielc got it. Sorry, I thought they had been fixed. @ghislaineguerin @RV-Adrian is there a card queued and this fix underway? I'd prefer to fix this and then ship so that we don't lose it. Thanks

**Comment by ghislaineguerin** [comment]
@ByronDarlison card is in doing and I'm working on it.

**Comment by ezequielc** [comment]
@ghislaineguerin Awesome, I will wait. Thanks!

**Comment by ghislaineguerin** [comment]
@ezequielc The editor bug is not a bug, that presentation has a placeholder in that position but we always had it like that. Please see any other presentation, no change needed. For the schedules list I have added a fix and will open a PR.

**Comment by ezequielc** [comment]
@alex-deaconu I update the styles and reviewed the staged version: https://apps-stage-0.risevision.com
I think we are good to deploy. Can I proceed? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . Thanks!

**Pull request merged**
