### PR TITLE
Migrate template editor controller

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Migrate template editor controller

[stage-2]

## Motivation and Context
Migrate the template editor controller to a component.

## How Has This Been Tested?
Tested locally. This is the starter PR for this change.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Convert the controller to a component and downgrade it.
Update the route to use the downgraded component.

Upgrade the directives on the template editor page.
Fix some scope inheritance issues.
Upgrade some other services and $transitions.

Use $transitions to check for $state changes.
Add beforeunload handler.

Create stub for common-header-height. Directive cannot be upgraded.

@ezequielc this is the initial PR for this. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good, but just a heads up, template editor is not loading on staging. 
I think I had a similar problem in the past due to compilation/resolution problem and had to use [this](https://github.com/Rise-Vision/rise-vision-apps/blob/master/src/app/template-editor/template-editor.module.ts#L18) workaround. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc thanks for the heads up 👍 , pushed the fix in the next PR. Thanks.

**Comment by ezequielc** [comment]
Sounds good, thanks!

**Review by ezequielc — APPROVED** [review]

**Pull request merged**
