### PR TITLE
Chore/test svc openid connect all functions

### PR DESCRIPTION
**Pull request by santiagonoguez**
## Description
Unit tests for the rest of the functions in svc-openid-connect.

## Motivation and Context
Coverage

## How Has This Been Tested?
This is a test.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Review by alex-deaconu — APPROVED** [review]
@santiagonoguez looks good, however I'm not sure why the coverage is still so low for this file: https://coveralls.io/builds/35732809/source?filename=web/scripts/components/userstate/services/svc-openid-connect.js.

**Comment by santiagonoguez** [comment]
@alex-deaconu could be that the loader is still not covered here ?

**Comment by alex-deaconu** [comment]
@santiagoarriaga no, it's still low after the loader tests: https://coveralls.io/builds/35736938/source?filename=web/scripts/components/userstate/services/svc-openid-connect.js. See red highlights lines for details. Thanks.

**Comment by santiagonoguez** [comment]
I see, weird :/

**Comment by alex-deaconu** [comment]
@santiagonoguez let's leave as is for now, I'll add a low priority note for taking a look later. Thanks.

**Pull request merged**
