### PR TITLE
Update angularjs version to 1.8

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Update angularjs version to 1.8

## Motivation and Context
Update to latest version

## How Has This Been Tested?
Smoke tested changes locally. Tests pass.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc @santiagonoguez please review. Thanks!

**Comment by santiagonoguez** [comment]
@alex-deaconu if I understand correctly, this is running on https://apps-beta.risevision.com/ 
right ?

**Comment by ezequielc** [comment]
@alex-deaconu I played a bit in betannad stage-11. Looks good to me. 👍

**Review by ezequielc — APPROVED** [review]

**Comment by alex-deaconu** [comment]
@santiagonoguez that is correct. Thanks.

**Pull request merged**
