### PR TITLE
Recommended Media Player updates

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps please review. Thanks!

**Comment by alex-deaconu** [comment]
Add a Display:
Screen Shot 2019-04-15 at 12 14 31 PM

Display was Added successfully:
Screen Shot 2019-04-15 at 12 02 25 PM

Preconfigured Media Player screen:
Screen Shot 2019-04-15 at 12 10 43 PM

Send to another Email screen:
Screen Shot 2019-04-15 at 12 09 51 PM

Set up your own Media Player (Windows):
Screen Shot 2019-04-15 at 12 02 57 PM

Set up your own Media Player (Chrome OS):
Screen Shot 2019-04-15 at 12 03 03 PM

**Comment by alex-deaconu** [comment]
@jasoncaldwell wondering if you could review the screens above. It basically summarizes the Add Display process in the modal.

To confirm, the Send to Another Email form was not provided in Zeplin so we left it as is.

Wondering if you could review and give us any feedback, or we're good to go!

Thanks.

**Comment by jasoncaldwell** [comment]
> @jasoncaldwell wondering if you could review the screens above. It basically summarizes the Add Display process in the modal. This is also staged on https://apps-stage-0.risevision.com if you want to see it live.
> 
> To confirm, the Send to Another Email form was not provided in Zeplin so we left it as is.
> 
> Wondering if you could review and give us any feedback, or we're good to go!
> 
> Thanks.

@alex-deaconu Thanks, I'll review it before EOD. One thing I see off the bat: watch the spelling of "Raspberry Pi".

**Comment by alex-deaconu** [comment]
@jasoncaldwell oh wow, that's been spelled like that from before. I will correct, good catch!

**Comment by jasoncaldwell** [comment]
> @jasoncaldwell oh wow, that's been spelled like that from before. I will correct, good catch!

@alex-deaconu Awesome, thanks!

Other than that, I see a few spacing/padding issues. Should I enumerate them here?

**Comment by alex-deaconu** [comment]
@jasoncaldwell that would be best, thanks!

**Comment by jasoncaldwell** [comment]
@alex-deaconu Please find the main discrepancies below. Let me know if there's any questions!

in-app_recommended_media_player_sketch-2
in-app_recommended_media_player_sketch-3
in-app_recommended_media_player_sketch-4
in-app_recommended_media_player_sketch

**Comment by ezequielc** [comment]
@jasoncaldwell Re. spacing issues, I see that @alex-deaconu and @olegrise are using utility classes that we have in the app. I am wondering if you are considering them on your designs or if you are setting specific spacing. 

Sorry for jumping in here, but I think we need to have clarity on this before we implement the suggested changes. Thanks!

**Comment by alex-deaconu** [comment]
Merging, will address the spacing issues in a subsequent PR. Thanks.

**Pull request merged**
