### PR TITLE
Infrastructure work for new pricing page

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Move Plan Selector to purchase flow, so that we can refactor it and easily remember steps/values.

Temporarily modified `purchaseFactory._init()` so that it remember steps when picking a different display's count. It will be refactored in the next PRs.

## Motivation and Context
Checkout flow epic

## How Has This Been Tested?
Validated case locally. Staged at [stage-1]

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Initial PR for moving pricing page to the purchase flow. It is functional but still needs cleanups and refactorings that I will be addressing in the next PRs. Please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc looks good, thanks for restaging!

**Comment by ezequielc** [comment]
@alex-deaconu This is ready to be released. Please review. Thanks!

**Review by alex-deaconu — APPROVED** [review]
@ezequielc looks good 👍

**Pull request merged**
