### PR TITLE
Fix duplicate user message

### PR DESCRIPTION
**Pull request by alex-deaconu**
[stage-1]

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Staged at https://apps-stage-0.risevision.com/

Removing message-box dependency as it is added to CH.

@ezequielc @fjvallarino please review. Thanks!

**Comment by alex-deaconu** [comment]
Quick update, this is re-staged at https://apps-stage-1.risevision.com/. Thanks.

**Comment by fjvallarino** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino FYI I've updated this branch to the latest CH version which includes the fix for Delete button in Tel type fields. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Pull request merged**
