### PR TITLE
Integrate rise-data-weather component

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc I think so. Will work on merging based on that assumption. Thanks.

**Comment by alex-deaconu** [comment]
@sheadarlison @mmeiers the Weather component UI is now ready for release. Wondering if you could take a quick look before we merge.

You can use our test template for this:
https://apps-stage-1.risevision.com/templates/edit/da027a6e-2de2-4b2d-bc66-4083c11d604c?cid=e1be58ad-da49-4a50-86b9-9baf2cabd261

To confirm, preview is not fully functional at this point. Here's a screenshot of how it would look like if it were:
Screen Shot 2019-05-23 at 11 13 58 AM

Thanks!

**Comment by sheadarlison** [comment]
@alex-deaconu Looks great, could you please add a colon after *Display weather in* so it's *Display weather in:* 

Sorry for the delayed response, I don't check Github notifications that often, in future if you need something faster can you tag me on a trello card.

Thanks

**Comment by alex-deaconu** [comment]
@sheadarlison no worries, will update, thanks!

**Comment by mmeiers** [comment]
@alex-deaconu Ui looks good. Curious Is the F its own element or is part of the degree data. 
Specifically, the first thing I would do as a designer is to add the degree symbol in front of F.
As long as the F is its own element I'm sure I could just add a CSS pseudo class: before to append it.

**Comment by alex-deaconu** [comment]
@mmeiers the report comes with 2 separate fields: the `temperature` and the `temperature_scale`. This way you should be able to add the degree symbol using CSS as you're describing. Thanks!

**Comment by alex-deaconu** [comment]
Thanks for the reviews guys! I've updated the colon as per Shea's note.

Merging. Thanks!

**Pull request merged**
