### PR TITLE
Set default names for component directives

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Set default names for component directives

Add component array and map utilities
Extend component directive and move common properties

[stage-18]

## Motivation and Context
Playlist UI

## How Has This Been Tested?
Tested locally. Updated test coverage. Will have another PR for more test coverage updates for `dtv-attribute-editor.js`.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. As mentioned I will submit another PR with improved test coverage. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I found a minor issue: when I open a presentation, the components icons don't appear in the list. They only appear after I navigate to the component and back. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc good find, I will take a look. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc thankfully the issue was the logo component was missing. Late Friday I noticed it wasn't working and I thought it was because of initialization, so I incorrectly moved the `angular.extend` code, and didn't test properly or confirm what the root of the issue was.

I validated this fixes both the missing icon issues as well as navigating to Image logo.

Please see the second commit.

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Nice! I tested and looks good 👍

**Review by ezequielc — APPROVED** [review]

**Pull request merged**
