### PR TITLE
Update CH version

### PR DESCRIPTION
**Pull request by ezequielc**
To support https://github.com/Rise-Vision/common-header/pull/1007
@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc 👍 . To confirm, a subsequent PR will address Display Address save? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Yes, I will open another PR for that. Thanks

**Comment by ezequielc** [comment]
@alex-deaconu I added a listener to company updated event and the address is re-sent to the Template when company is updated. Please review. Thanks!

https://apps-stage-1.risevision.com

**Comment by alex-deaconu** [comment]
@ezequielc looks great! Thanks for fixing 👍

**Pull request merged**
