### PR TITLE
Add Url validator to slides widget settings

### PR DESCRIPTION
**Pull request by rodrigopavezi**
- Unit test
- E2E tests
[stage-6]

You can see on https://apps-stage-6.risevision.com/

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@rudibravo @jungeunyoon could you please review and feel free to merge it or continue to work on it as I will be off from tomorrow and only be back on Monday. cheers

**Comment by rodrigopavezi** [comment]
[I can see that what I have provided is correct [3]](https://trello.com/c/xQ9zgPc3/5007-i-can-see-that-what-i-have-provided-is-correct-3)

**Comment by rudibravo** [comment]
@jungeunyoon personally I don't think it's required for this PR since it's still going to be reviewed on the main PR, which apps is tagged.

**Comment by jungeunyoon** [comment]
@rudibravo ah missed that. good point 👍

**Pull request merged**
