### PR TITLE
Use HTTPS for Rise Player download links

### LINKED ISSUE #2163: Not all the download player links work in-apps
https://www.screencast.com/t/tLkmCbQpWu

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Use HTTPS links to download players to prevent Chrome 86 blocks.

## Motivation and Context
Fix #2163

## How Has This Been Tested?
Locally and on [stage-20]

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Please review. Pending confirmation with Alan on the link URL. Thanks

**Review by alex-deaconu — APPROVED** [review]
@ezequielc 👍

**Comment by ezequielc** [comment]
@alex-deaconu By the way, there is no need to update Core emails as they have links to the Help Center articles, not direct download links. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc nice, thanks for double checking!

**Pull request merged**
