### PR TITLE
Open Presentation Properties when clicking presentation name

### PR DESCRIPTION
**Pull request by ezequielc**
@fjvallarino Please review. Thanks

### CODE REVIEW

**Comment by fjvallarino** [comment]
@ezequielc would it make sense to switch the cursor to indicate the element is clickable?

**Comment by ezequielc** [comment]
@fjvallarino Yes, I think so. 
I also checked google docs and they keep the same text cursor, but highlight the element. But it is an inline edit in their case.
@ghislaineguerin What to you think? Thanks

**Comment by ezequielc** [comment]
@ghislaineguerin Actually, if you think we should add the pointer, we could merge this PR and add the pointer in your open CS PR. Thoughts? Thanks

**Comment by ghislaineguerin** [comment]
@ezequielc that's a good idea. I will add the pointer to my common styles PR.

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
