### PR TITLE
Playlist tooltips

### PR DESCRIPTION
**Pull request by ezequielc**
- Tooltips for Playlist Items: Duplicate, Delete and Duration
- Artboard Empty State (help image) for a new blank Presentation (not from Template)
- Tooltip pops up when closing presentation properties:
  - On Add Placeholder button for a new blank Presentation
  - On first Placeholder when new Presentation from a Template

@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc just playing with the deployed version, the tooltip popup seems to sometimes block clicking on the actual button. I think the animation + container from the tooltip is receiving the click event rather than the button itself: http://screencast.com/t/oUqqO4zC. Can you take a look? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Thanks, I will take a look. Maybe we should bounce only for the first time, right after we close Presentation Properties, on mouse enter, there is no need to bounce. If you agree, I will try to implement that. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc one bounce works for me. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Updated the behaviour, now it only bounces by the event of closing Presentation Properties. Please review. Thanks
@settinghead fyi

**Comment by alex-deaconu** [comment]
@ezequielc looks good. Thanks for fixing 👍

**Pull request merged**
