### PR TITLE
Make billingContactsEmails field editable

### PR DESCRIPTION
**Pull request by fjvallarino**
Can be tested with: https://apps-stage-1.risevision.com/?cid=a847f5bb-e61a-4925-817a-552075edf203, after opening Company Settings modal.

@Rise-Vision/apps please review

### CODE REVIEW

**Comment by fjvallarino** [comment]
@Rise-Vision/apps updated

**Comment by alex-deaconu** [comment]
@fjvallarino looks good 👍

**Comment by alex-deaconu** [comment]
@fjvallarino actually, what happened to cleaning out the ng-tags-input field from the Apps repo, as it will be loaded with CH? Thanks.

**Comment by alex-deaconu** [comment]
@fjvallarino looks good, thanks for correcting!

**Pull request merged**
