### PR TITLE
Add MAC Address field and UX changes to Displays page

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps please review

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps the right aligned buttons look so weird to me: https://screencast.com/t/RDALDy7PlP7. Is that intentional? Thoughts? Thanks.

**Comment by adrianDD** [comment]
@alex-deaconu @fjvallarino 
That's as prototyped, just to fall in line with the button locations above.
Full-width didn't add up here. 
I do think the 'Download Rise Player' component can use a re-do at some point.
image

**Comment by alex-deaconu** [comment]
@adrianDD okay, no problem. I just thought right align looked weird & new pattern; currently the fields are right aligned so maybe I'm just used to that pattern. Thanks.

**Comment by alex-deaconu** [comment]
@fjvallarino looks good 👍 .

Not sure if you want to merge or hold off until the "Hide empty table sections" card is implemented.

Thanks.

**Comment by adrianDD** [comment]
@alex-deaconu woops, wrong git account :)

Yeah, I did consider it.. and our most common UI pattern is actually a right-align for related actions.. but I do agree the dropdown of buttons is a little jarring. I think we can do better overall with accessing these player files, and I'll note that 👍 

re: Hide tables, I think there's a bit of discussion that needs to happen on that one but I'll leave that up to Apps :)

**Comment by fjvallarino** [comment]
@alex-deaconu @ezequielc what should I do regarding @RV-Adrian latest comment? 

> Hide tables, I think there's a bit of discussion that needs to happen on that one but I'll leave that up to Apps :)

**Comment by RV-Adrian** [comment]
@fjvallarino @ezequielc 
I'll clarify a bit on the card on 'hide tables'. I think that's best-suited to tackle when the rest of the Offline Play UI is ready to go, because the idea is to hide entire sections when they are simply empty. 
With the UI on this PR, rows could be hidden.. but I think the usefulness is not as great (imo)
Thanks, and let me know if that doesn't add up.
image

**Comment by ezequielc** [comment]
@RV-Adrian @fjvallarino I do think we can hide Serial Number and MAC address fields when empty for now. We can discuss hiding tables whenever we implement the next layout. Thanks

**Comment by adrianDD** [comment]
@ezequielc Sounds good, thanks

**Comment by fjvallarino** [comment]
@Rise-Vision/apps updated

**Comment by alex-deaconu** [comment]
@fjvallarino looks good, thanks for fixing 👍

**Pull request merged**
