### PR TITLE
New service for handling plans

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
New service for handling plans

[stage-15]

## Motivation and Context
Prevent code duplication.

## How Has This Been Tested?
Tested changes locally. Updated unit tests.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Utilities that I will use in my next PR.

@ezequielc @santiagonoguez please review. Thanks!

**Review by santiagonoguez — APPROVED** [review]
@alex-deaconu changes look good to me :D

**Comment by alex-deaconu** [comment]
@santiagonoguez thanks, I'll wait for @ezequielc to review this one as well, since there's some important functionality being touched. Thanks.

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Looks good to me as well 👍

**Pull request merged**
