### PR TITLE
New file selector layout

### PR DESCRIPTION
**Pull request by ezequielc**
New layout for Storage Selector.

@alex-deaconu I am not going to merge as we need to implement breadcrumbs and maybe thumbnails too before releasing. We can work from this branch for the additional features. Please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc code looks good 👍 . Not liking the look of Storage Full as per the discussion in the card. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Staged at https://apps-stage-0.risevision.com
Are we good to release? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc just a reminder that the common-i18n branch needs to be merged. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Updated. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc looks good 👍 . Thanks!

**Pull request merged**
