### PR TITLE
Chore/test open id connect loader

### PR DESCRIPTION
**Pull request by santiagonoguez**
## Description
Unit test for open id connect loader 

## Motivation and Context
Unit test coverage

## How Has This Been Tested?
This is a test, no runtime changes.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Review by alex-deaconu — APPROVED** [review]
@santiagonoguez looks good. Do you think it's worth splitting the `svc-openid-connect-loader.js` into its own js file? Thanks.

**Comment by santiagonoguez** [comment]
@alex-deaconu the mocks and services are mostly unrelated, that's why I separated it. I can join them though if you think it's more clear ( for example, when searching for the test code of the file ).

**Comment by alex-deaconu** [comment]
No, I meant the other way, split out the loader from the original JS file.

**Comment by santiagonoguez** [comment]
Oh, I see. I'm ok with it either way. 

The whole file is less than 200 lines, which I think it's pretty decent. Thanks !

**Pull request merged**
