### PR TITLE
Feature/video experiment

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@fjvallarino @alex-deaconu 
I am having issues with this branch. I took a look and the Schedule does seem to get created, despite the error. Will bring this up in standup tomorrow, thanks.
https://apps-stage-3.risevision.com

@ezequielc FYI

**Comment by RV-Adrian** [comment]
@alex-deaconu @fjvallarino 
e2e issue fixed, PR good for review now 🎆 
https://apps-stage-3.risevision.com

@ezequielc I believe this PR would also cover https://trello.com/c/VeWVSbQ6/2076-revert-blank-presentation-experiment-1

**Comment by fjvallarino** [comment]
@RV-Adrian looks good! I assume we're not using common-18n because this is an experiment. If that's expected, then :+1: 

Only concern is the video is not in High Definition.

**Comment by RV-Adrian** [comment]
@fjvallarino Good point. I assumed not to use common-i18n as well, but will do so if there's a good reason.

**Comment by ezequielc** [comment]
@RV-Adrian As it is an experiment, we are good to not use common-i18n. We are probably changing this page again next week. Thanks

**Comment by RV-Adrian** [comment]
@ezequielc Sounds good

**Comment by alex-deaconu** [comment]
@RV-Adrian I have a similar concern regarding the inline styles. Can't you re-use a common-style class for the paddings? Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Missed that one. Easily removed (didn't really do much).
Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian got it, thanks for fixing! Looks good 👍.

**Pull request merged**
