### PR TITLE
Send user company role on identify, logged in and user updated events

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Send user company role on `identify()`, `logged in` and `User Updated` events.

## Motivation and Context
https://trello.com/c/RlfB1tKI/6373-add-user-role-to-identify-and-log-in-event-1

## How Has This Been Tested?
Locally and on [stage-19].

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc we actually have a custom Company Role collection modal which saves the User here: https://github.com/Rise-Vision/rise-vision-apps/blob/master/web/scripts/common-header/services/svc-company-icp.js#L164. Wondering if we should add tracking for this as well. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc maybe we can move the tracking outside of the controller to the updateUser service? Just an idea. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Good catch, I missed that one. I will updated it and see if it is worth moving the track to the factory. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Updated as per suggestion. Please review the last 2 commits. Thanks!

**Pull request merged**
