### PR TITLE
Fix some unit tests; remove auth2 client loader

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Fix some unit tests; remove auth2 client loader

[stage-19]

## Motivation and Context
WIP for unit test fixes.

## How Has This Been Tested?
Fixed tests pass.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
WIP for fixing and updating tests.

@ezequielc @santiagonoguez please review. Thanks!

**Review by santiagonoguez — APPROVED** [review]

**Comment by alex-deaconu** [comment]
@ezequielc @santiagonoguez I've pushed a second commit that fixes or disables the remaining unit tests. Let's see how the e2e tests do. Please review. Thanks!

**Review by santiagonoguez — APPROVED** [review]
@alex-deaconu looks good to me, thanks !

so the idea is to enable those little by little as soon as they get fixed, right ?

**Comment by alex-deaconu** [comment]
@santiagonoguez yeah that's the plan. 1 test suite is disabled because of a critical failure for overwriting the `$window` object (attribute-editor). The other 2 are failing because of changes related to the epic. Thanks.

**Comment by alex-deaconu** [comment]
Tests passed!

**Review by ezequielc — APPROVED** [review]
Awesome 👍

**Pull request merged**
