### PR TITLE
Add new last modified column

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Add new last modified column

Update border style, add horizontal scrolling
Fix widths

[stage-16]

## Motivation and Context
Network management epic.

## How Has This Been Tested?
Tested changes locally at various resolutions.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Your changes look good, but I think we have a problem with `lastModified` field here. The username part of it is null for some displays:
Screen Shot 2020-09-23 at 5 30 33 PM

Maybe it is an issue with Test environment only, but we should double check before releasing to production. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc oops, I was using the field as returned form the Core. I will update to use the composite fields form the response. Good catch. Thanks.

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Thanks for the update 👍

**Pull request merged**
